--- 
version: "3"
services: 
  angular: 
    build: CplayerUI
    container_name: angular-docker
    image: shivaagn/angular-app:new
    network_mode: host
    ports: 
      - "4200:4200"
    restart: always
  favourites: 
    build: 
      context: demo/
    image: shivaagn/favourites:v2
    network_mode: host
    ports: 
      - "8002:8002"
    restart: always
